version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: '__TASK_DEFINITION_FAMILY__'
          ContainerPort: 80
        PlatformVersion: '1.4.0'
